### ISSUE TITLE
crackerDiameter package missing and util package needs update

### ISSUE THREAD

**Issue by hsuk-404** [hpclab/cracker#1]
crackerDiameter.DiameterTreeMessageRedPhase
crackerDiameter.DiameterTreeMessageBluePhase
CrackerStats.scala

To run CrackerAllOptimizations, few above files are missing and looks like the util package also needs update.

**Comment by alessandrolulli** [comment]
The following dependencies have been remove from CrackerStats.scala because not necessary:
*) crackerDiameter.DiameterTreeMessageRedPhase
*) crackerDiameter.DiameterTreeMessageBluePhase

Also, the util package has been updated.
Added pom.xml, it is now possible to build the branch optimizations with Maven.
